### ISSUE TITLE
 unmarshaling response: json

### ISSUE THREAD

**Issue by burjuyz** [kutovoys/marzban-exporter#1]
Версия marzbana v0.4.4
image: gozargah/marzban:dev
В логах насыпает 
2024/03/20 09:09:35 Error unmarshaling response: json: cannot unmarshal number into Go struct field User.users.expire of type string

**Comment by kutovoys** [comment]
@burjuyz Спасибо за issue 
Повторил у себя. 
Проблема в том что я неправильно обрабатываю поле expire от api.
Поправлю к следующему релизу, заодно добавив новые метрики по expire подписок.

**Comment by kutovoys** [comment]
Пофиксил в  f0a57ff 
Заодно добавил новую метрику: marzban_user_expiration_date
